development:
   host: staff.mongohq.com
   port: 10004
   username: mongo_thom
   password: mongo_thom
   database: ey_mongo_dev

# test:
#    host: staff.mongohq.com
#    port: 10004
#    username: mongo_thom
#    password: mongo_thom
#    database: ey_mongo_test

# set these environment variables on your prod server
production:
  host: staff.mongohq.com
  port: 10036
  username: mongo_thom
  password: mongo_thom
  database: ey_mongo_prod
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
